### ISSUE TITLE
Make the Dom

### ISSUE THREAD

**Issue by Zead-Ashraf** [zebra-not-donkey/tip-calculator-app-main#4]

**Comment by Zead-Ashraf** [comment]
دى بقا مهمتك يا مارو

**Comment by Zead-Ashraf** [comment]
هنا نقدر نتناقش
بدل تيلجرام

**Comment by Zead-Ashraf** [comment]
**متقلقش الموضوع سهل يعنى**

**Comment by marwanzayed** [comment]
لا التيلجرام اسهل من هنا

**Comment by Zead-Ashraf** [comment]
لا بالعكس
على الاقل هنا انت عارف انها مساحة عمل
وكمان فيه خواص حلوة زى أنى أو انك اعملى أو اعملك to do list بالمشاكل اللى هتتحل و تبقى قدامى
خلينا هنا احسن يعنى لو مناقشة فى ال issue

**Comment by marwanzayed** [comment]
انا مش عارف اعمل الDOM

**Comment by marwanzayed** [comment]
فا معلش

**Comment by Zead-Ashraf** [comment]
finished
