### ISSUE TITLE
Make the page responsive

### ISSUE THREAD

**Issue by Zead-Ashraf** [zebra-not-donkey/tip-calculator-app-main#8]

**Comment by marwanzayed** [comment]
شوف انا وصلت لفين

**Comment by marwanzayed** [comment]
انا خلصت responsive كامل هكمل الjs بكره

**Comment by marwanzayed** [comment]
انا خلصت الريسبونسف للموقع كامل و هكمل الجافا سكربت بكره عشان تعبت فا ادخل راجع الكود و شوف انا عملت ايه
